---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  PORT: "3001"
  API_HOST: "node-api.default.svc.cluster.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web
  labels:
    app: node-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-web
  template:
    metadata:
      labels:
        app: node-web
    spec:
      containers:
      - name: node-web
        imagePullPolicy: Always
        image: us-central1-docker.pkg.dev/gcp-classes-395503/my-first-docker-registry/web:latest
        envFrom:
        - configMapRef:
            name: web-config
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: node-web
spec:
  type: LoadBalancer
  selector:
    app: node-web
  ports:
  - name: http
    port: 80
    targetPort: 3001

